apiVersion: batch/v1
kind: Job
metadata:
  name: serverless-simulaion
  labels:
    app: serverless-simulaion
  namespace: ml-infra
spec:
  template:
    metadata:
      name: serverless-simulaion
      labels:
        app: serverless-simulaion
    spec:
      restartPolicy: Never
      containers:
      - name: scaler
        image: autra-cn-beijing.cr.volces.com/autra/volcengine/wei_scaler_test:v1.0
        command: ["./run.sh"]
      - name: serverless-simulator
        # registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.3.1
        image: autra-cn-beijing.cr.volces.com/autra/volcengine/wei_simulator_test:v1.0
        command: ["./run.sh" ]
        # args: ["function_smoke_test"]
        args: ["dataSet_1"]
