apiVersion: batch/v1
kind: Job
metadata:
  name: serverless-simulaion
  labels:
    app: serverless-simulaion
spec:
  template:
    metadata:
      name: serverless-simulaion
      labels:
        app: serverless-simulaion
    spec:
      restartPolicy: Never
      containers:
        - name: scaler
          #  需要替换为选手实现的scaler镜像地址
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/scaler:v0.7.1
          command: ["./run.sh"]
        - name: serverless-simulator
          image: registry.cn-beijing.aliyuncs.com/cloudnative-challenge/simulator:v1.2.1
          command: ["./run.sh" ]
         # 需要替换为选手希望测试的数据集名称，数据集的名称可以参考data/data_trainning.tar.gz解压后的目录结构
         # 不填写参数时，默认会测试所有的数据集
          args: ["function_smoke_test"]
